### ISSUE TITLE
No GPG key for the Apt repo

### ISSUE THREAD

**Issue by wilb** [ThoughtWorksInc/go-cookbook#39]
The apt repo appears to be signed but the recipe to set up the repo doesn't add a key. I can't seem to find where to retrieve the key for it to allow me to fix & PR. For yum it looks like you are disabling the gpgcheck...

As a result every time apt updates its package repos I get the expected error:

W: GPG error: http://dl.bintray.com  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9149B0A6173454C7

**Comment by Tpbrown** [comment]
@wilb - thanks for catching this.    When the repos initially came up the packages weren't signed.

I hadn't realized that's been changed.  It looks like the key is sitting on the repo too - Release.gpg? http://dl.bintray.com/gocd/gocd-deb/ 

I dont' see a key for the yum repo, and haven't checked to see if it's signed.

I can't get this updated for a week or so, but happy to take a PR.

**Comment by wilb** [comment]
Release.gpg is just the GPG signed Release file, apt uses this to verify the authenticity of the packages - this is where the check is failing because the pubkey hasn't been made available to apt, as documented here: https://wiki.debian.org/SecureApt

Will happily PR but need the pubkey location as it doesn't appear to be on the usual public key servers.

**Comment by tiwoc** [comment]
Could you please upload the public key to the key servers and/or provide it on your download page? I'm automating the installation of go.cd and would like APT to check whether the packages has been manipulated.

**Comment by wilb** [comment]
@Tpbrown would it be possible to tag the maintainer of your apt repo in this thread so they can help resolve?

**Comment by wilb** [comment]
I've added the key to the agent_linux recipe and created a pull request.
